#define Boolean             bool
#define Interger            int
#define Double              float
#define Foremost            main
#define During              while
#define If                  if
#define Or_Else             else
#define Left_Parenthesis    (
#define Right_Parenthesis   )
#define Semicolon           ;
#define Left_Bracket        {
#define Right_Bracket       }
#define Scope_Resoulution   ::
#define Addition            +
#define Subtraction         -
#define Multiplication      *
#define Division            /
#define Point               .
#define Greater_Than        >
#define Less_Than           <
#define Equals              =
#define Greater_Than_Or_Equal_To       =>
#define Less_Than_Or_Equal_To          =<
#define Do                  do
#define Cutoff              break
#define Change              switch
#define Original            default
#define Do_This_For         for
#define Bring_Back          return
